[[spring-mvc-test-server-static-imports]]
====== 静态导入
上述例子中，使用了一些静态导入（staitc imports），例如
 `MockMvcRequestBuilders.*` , `MockMvcResultMatchers.*` , 和 
`MockMvcBuilders.*` 。想找到这些类，有个简单的办法是搜索 __“MockMvc*”__ 。如果使用Eclipse，
请在Eclipse 的 preferences 菜单中找到 __Java → Editor → Content Assist → Favorites__，
把这些类加入至“favorite static members”，那样就能在敲入这些静态方法的第一个字母时给出代码提示。
其他IDE（例如 InteliJ）可能不需要额外的配置，请参考各自的帮助文档。

[[spring-mvc-test-server-setup-options]]
====== Setup 装配选项

服务器端的测试setup是为了创建一个能发起请求的 `MockMvc` 实例。有两种创建的办法（选项）

第一种办法是通过 __TestContext__ 框架指向 Spring MVC 的配置文件，框架将配置载入并把 `WebApplicationContext` 注入至 测试类，
从而创建一个 `MockMvc` 。

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	@RunWith(SpringJUnit4ClassRunner.class)
	@WebAppConfiguration
	@ContextConfiguration("my-servlet-context.xml")
	public class MyWebTests {

		@Autowired
		private WebApplicationContext wac;

		private MockMvc mockMvc;

		@Before
		public void setup() {
			this.mockMvc = MockMvcBuilders.webAppContextSetup(this.wac).build();
		}

		// ...

	}
----

另一种办法是简单地将被测试的Controller 实例注册至 MockMvc，而不加载任何配置，那样测试框架会自动创建一个
合适的基础 Spring MVC 配置给 Controller 。自动创建的配置可与通过 MVC JavaConfig（以及MVC命名空间）
创建的配置相提并论，并且可以通过构造器风格的方法进行一定程度的定制化:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class MyWebTests {

		private MockMvc mockMvc;

		@Before
		public void setup() {
			this.mockMvc = MockMvcBuilders.standaloneSetup(new AccountController()).build();
		}

		// ...

	}
----

你该使用那种方式呢？

第一种方式 __“webAppContextSetup”__ 会加载实际的Spring MVC 配置，实现一个更完整的集成测试。
因为 __TestContext 框架__ 会缓存已载入的Spring配置，所以即使加入更多的测试用例，整个测试过程也能运行的比较快。
此外，你还可以通过 Spring 配置注入一个模拟service对象至Controller中，从而可以专注于web 层的测试。下面是一个使用了 Mockito 的例子。

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<bean id="accountService" class="org.mockito.Mockito" factory-method="mock">
		<constructor-arg value="org.example.AccountService"/>
	</bean>
----

然后就可以将模拟service对象注入至测试代码中，组装并验证测试是否符合期望结果

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	@RunWith(SpringJUnit4ClassRunner.class)
	@WebAppConfiguration
	@ContextConfiguration("test-servlet-context.xml")
	public class AccountTests {

		@Autowired
		private WebApplicationContext wac;

		private MockMvc mockMvc;

		@Autowired
		private AccountService accountService;

		// ...

	}
----

从另一个角度看，__“standaloneSetup”__ 更像单元测试：一次测试一个Controller，Controller可以被手动注入模拟的依赖，
也不会加载Spring配置。这样的测试从形式上来说更加专注、更容易看出某个Controller是否被测试了、
是否要做某些特定的Spring MVC 配置，等等。要写一个即席ad-hoc测试去验证某些行为或debug某个问题时，
“standaloneSetup”是一个很方便的办法。

正如集成测试与单元测试之争，上面两种测试方式也没有对错之分。
使用“standaloneSetup”的确需要某些额外的“webAppContextSetup”去验证 Spring MVC 的配置。
另一方面，你也可以把“webAppContextSetup”与所有测试代码整合在一起，使用实际的Spring MVC 配置去测试。