[[oxm-castor]]
=== Castor
Castor XML mapping is an open source XML binding framework. It allows you to transform
the data contained in a java object model into/from an XML document. By default, it does
not require any further configuration, though a mapping file can be used to have more
control over the behavior of Castor.

For more information on Castor, refer to the
http://castor.codehaus.org/xml-framework.html[__Castor web site__]. The Spring
integration classes reside in the `org.springframework.oxm.castor` package.



[[oxm-castor-marshaller]]
==== CastorMarshaller
As with JAXB, the `CastorMarshaller` implements both the `Marshaller` and `Unmarshaller`
interface. It can be wired up as follows:

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<beans>
		<bean id="castorMarshaller" class="org.springframework.oxm.castor.CastorMarshaller" />
		...
	</beans>
----



[[oxm-castor-mapping]]
==== Mapping
Although it is possible to rely on Castor's default marshalling behavior, it might be
necessary to have more control over it. This can be accomplished using a Castor mapping
file. For more information, refer to http://castor.codehaus.org/xml-mapping.html[Castor
XML Mapping].

The mapping can be set using the `mappingLocation` resource property, indicated below
with a classpath resource.

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<beans>
		<bean id="castorMarshaller" class="org.springframework.oxm.castor.CastorMarshaller" >
			<property name="mappingLocation" value="classpath:mapping.xml" />
		</bean>
	</beans>
----


[[oxm-castor-xsd]]
===== XML Schema-based Configuration
The `castor-marshaller` tag configures a
`org.springframework.oxm.castor.CastorMarshaller`. Here is an example:

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<oxm:castor-marshaller id="marshaller" mapping-location="classpath:org/springframework/oxm/castor/mapping.xml"/>
----

The marshaller instance can be configured in two ways, by specifying either the location
of a mapping file (through the `mapping-location` property), or by identifying Java
POJOs (through the `target-class` or `target-package` properties) for which there exist
corresponding XML descriptor classes. The latter way is usually used in conjunction with
XML code generation from XML schemas.

Available attributes are:

|===
| Attribute| Description| Required

| `id`
| the id of the marshaller
| no

| `encoding`
| the encoding to use for unmarshalling from XML
| no

| `target-class`
| a Java class name for a POJO for which an XML class descriptor is available (as
  generated through code generation)
| no

| `target-package`
| a Java package name that identifies a package that contains POJOs and their
  corresponding Castor XML descriptor classes (as generated through code generation from
  XML schemas)
| no

| `mapping-location`
| location of a Castor XML mapping file
| no
|===




