[[dynamic-language-beans-inline]]
===== Inline dynamic language source files
The dynamic language support can also cater for dynamic language source files that are
embedded directly in Spring bean definitions. More specifically, the
`<lang:inline-script/>` element allows you to define dynamic language source immediately
inside a Spring configuration file. An example will perhaps make the inline script
feature crystal clear:

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<lang:groovy id="messenger">
		<lang:inline-script>

	package org.springframework.scripting.groovy;

	import org.springframework.scripting.Messenger

	class GroovyMessenger implements Messenger {
		String message
	}

		</lang:inline-script>
		<lang:property name="message" value="I Can Do The Frug" />
	</lang:groovy>
----

If we put to one side the issues surrounding whether it is good practice to define
dynamic language source inside a Spring configuration file, the `<lang:inline-script/>`
element can be useful in some scenarios. For instance, we might want to quickly add a
Spring `Validator` implementation to a Spring MVC `Controller`. This is but a moment's
work using inline source. (See <<dynamic-language-scenarios-validators>> for such an
example.)

Find below an example of defining the source for a JRuby-based bean directly in a Spring
XML configuration file using the `inline:` notation. (Notice the use of the &lt;
characters to denote a `'<'` character. In such a case surrounding the inline source in
a `<![CDATA[]]>` region might be better.)

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<lang:jruby id="messenger" script-interfaces="org.springframework.scripting.Messenger">
		<lang:inline-script>

	require 'java'

	include_class 'org.springframework.scripting.Messenger'

	class RubyMessenger &lt; Messenger

		def setMessage(message)
			@@message = message
		end

		def getMessage
			@@message
		end

	end

			</lang:inline-script>
		<lang:property name="message" value="Hello World!" />
	</lang:jruby>
----


