[[dynamic-language-beans-jruby]]
==== JRuby beans

.The JRuby library dependencies
****
The JRuby scripting support in Spring requires the following libraries to be on the
classpath of your application.

* `jruby.jar`
****

From the JRuby homepage...

"__JRuby is an 100% pure-Java implementation of the Ruby programming language.__"

In keeping with the Spring philosophy of offering choice, Spring's dynamic language
support also supports beans defined in the JRuby language. The JRuby language is based
on the quite intuitive Ruby language, and has support for inline regular expressions,
blocks (closures), and a whole host of other features that do make solutions for some
domain problems a whole lot easier to develop.

The implementation of the JRuby dynamic language support in Spring is interesting in
that what happens is this: Spring creates a JDK dynamic proxy implementing all of the
interfaces that are specified in the `'script-interfaces'` attribute value of the
`<lang:ruby>` element (this is why you __must__ supply at least one interface in the
value of the attribute, and (accordingly) program to interfaces when using JRuby-backed
beans).

Let us look at a fully working example of using a JRuby-based bean. Here is the JRuby
implementation of the `Messenger` interface that was defined earlier in this chapter
(for your convenience it is repeated below).

[source,ruby,indent=0]
[subs="verbatim,quotes"]
----
	package org.springframework.scripting;

	public interface Messenger {

		String getMessage();

	}
----

[source,ruby,indent=0]
[subs="verbatim,quotes"]
----
	require 'java'

	class RubyMessenger
		include org.springframework.scripting.Messenger

		def setMessage(message)
			@@message = message
		end

		def getMessage
			@@message
		end
	end

	# this last line is not essential (but see below)
	RubyMessenger.new
----

And here is the Spring XML that defines an instance of the `RubyMessenger` JRuby bean.

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<lang:jruby id="messageService"
			script-interfaces="org.springframework.scripting.Messenger"
			script-source="classpath:RubyMessenger.rb">

		<lang:property name="message" value="Hello World!" />

	</lang:jruby>
----

Take note of the last line of that JRuby source ( `'RubyMessenger.new'`). When using
JRuby in the context of Spring's dynamic language support, you are encouraged to
instantiate and return a new instance of the JRuby class that you want to use as a
dynamic-language-backed bean as the result of the execution of your JRuby source. You
can achieve this by simply instantiating a new instance of your JRuby class on the last
line of the source file like so:

[source,ruby,indent=0]
[subs="verbatim,quotes"]
----
	require 'java'

	include_class 'org.springframework.scripting.Messenger'

	# class definition same as above...

	# instantiate and return a new instance of the RubyMessenger class
	RubyMessenger.new
----

If you forget to do this, it is not the end of the world; this will however result in
Spring having to trawl (reflectively) through the type representation of your JRuby
class looking for a class to instantiate. In the grand scheme of things this will be so
fast that you'll never notice it, but it is something that can be avoided by simply
having a line such as the one above as the last line of your JRuby script. If you don't
supply such a line, or if Spring cannot find a JRuby class in your script to instantiate
then an opaque `ScriptCompilationException` will be thrown immediately after the source
is executed by the JRuby interpreter. The key text that identifies this as the root
cause of an exception can be found immediately below (so if your Spring container throws
the following exception when creating your dynamic-language-backed bean and the
following text is there in the corresponding stacktrace, this will hopefully allow you
to identify and then easily rectify the issue):

[literal]
[subs="verbatim,quotes"]
----
org.springframework.scripting.ScriptCompilationException: Compilation of JRuby script returned ''
----

To rectify this, simply instantiate a new instance of whichever class you want to expose
as a JRuby-dynamic-language-backed bean (as shown above). Please also note that you can
actually define as many classes and objects as you want in your JRuby script; what is
important is that the source file as a whole must return an object (for Spring to
configure).

See <<dynamic-language-scenarios>> for some scenarios where you might want to use
JRuby-based beans.



