[[beans-definition]]
=== Bean概述
一个Spring IoC容器管理了一个或者多个 __beans__。这些beans通过你提供给容器的配置元数据进行创建，例如通过XML形式的`<bean/>`定义。

在容器内本身，这些bean定义表示为`BeanDefinition`对象，它包含了如下的元数据：

* __包限定的类名：__ 通常是bean定义的实现类。
* Bean行为配置元素，这些状态指示bean在容器中的行为（范围，生命周期回调函数，等等）。
* bean工作需要引用的其他beans；这些引用也称为 __协作者__ 或 __依赖者__。
* 其他配置设置应用于新创建的对象中设置，例如连接池中的连接数或者连接池的大小限制。

这些元数据转换成组成每个bean定义的一组属性。

[[beans-factory-bean-definition-tbl]]
.bean定义
|===
| 属性名| 说明...

| class
| <<beans-factory-class>>

| name
| <<beans-beanname>>

| scope
| <<beans-factory-scopes>>

| constructor arguments
| <<beans-factory-collaborators>>

| properties
| <<beans-factory-collaborators>>

| autowiring mode
| <<beans-factory-autowire>>

| lazy-initialization mode
| <<beans-factory-lazy-init>>

| initialization method
| <<beans-factory-lifecycle-initializingbean>>

| destruction method
| <<beans-factory-lifecycle-disposablebean>>
|===

除了bean定义外，它还包含有关如何创建特定bean的信息，`ApplicationContext`实现还允许由用户在容器外创建注册现有的对象。
这是通过访问ApplicationContext的工厂方法，通过`getBeanFactory()`返回`DefaultListableBeanFactory`工厂方法的实现。
`DefaultListableBeanFactory`支持通过`registerSingleton(..)`方法和`registerBeanDefinition(..)`方法进行注册。
然而，典型的应用程序的工作仅仅通过元数据定义的bean定义beans。

[[beans-beanname]]
==== bean的命名
每个bean都有一个或多个标识符，这些bean的标识符在它所在的容器中必须唯一。
一个bean通常只有一个标识符，但如果它有一个以上的`id`标识符，多余的标识符将被认为是别名。

基于xml的配置元数据中，你可以使用`id` 或（和） `name` 属性来指定bean的标识符。
`id`属性允许您只指定一个id。通常这些名字是字母数字组成的（'myBean','fooService'等等），但也可能包含特殊字符。
如果你想给bean添加其他的别名，你可以通过`name`属性来指定这些别名，可以使用逗号(`,`)，分号(`;`)或者空格来分割这些别名。
这里需要特别注意的是，在Spring3.1版本以前，`id`属性被定义成`xsd:ID`类型（可以通过xml规则限制唯一），
在Spring3.1以及以后的版本中，`id`被定义成了`xsd:string`类型，`id`属性不在通过XML解析器限制为唯一，而是通过容器强制限制为唯一。

bean的id和name不是必须的。如果没有明确的name或者id，容易会给bean生成一个唯一的名字。
但是，如果你想通过名称引用这个bean，通过使用`ref`元素或<<beans-servicelocator,服务定位器模式>> 查找，你就必须提供一个名字。

不提供名称的原因和<<beans-inner-beans,内部beans>>和<<beans-factory-autowire,自动装配>>有关。

.Bean命名约定
****
该公约使用标准的Java实例字段名称命名beans。也就是说bean名字由一个小写字母开头，后面采用驼峰式命名规则。
这种名字如（不包含引号）：`'accountManager'`、
`'accountService'`、`'userDao'`、`'loginController'`等等。

一致的beans命名可以让您的配置容易阅读和理解，如果你正在使用Spring AOP，当你通过beans名称应用到advice时，这会对你帮助很大。
****


[[beans-beanname-alias]]
===== bean的别名
在对bean定义时，除了使用`id`属性指定一个唯一的名称外，为了提供多个名称，需要通过`name`属性加以指定，所有这个名称都指向同一个bean，在某些情况下提供别名非常有用，比如为了让应用每一个组件都能更容易的对公共组件进行引用。然而，在定义bean时就指定所有的别名并不总是很恰当。有时我们期望能够在当前位置为那些在别处定义的bean引入别名。在XML配置文件中，可以通过`<alias/>`元素来完成bean别名的定义，例如：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<alias name="fromName" alias="toName"/>
----

在这种情况下，如果容易中存在名为`fromName`的bean定义，在增加别名定义后，也可以用`toName`来引用。

例如，在子系统A中通过名字`subsystemA-dataSource`配置的数据源。在子系统B中可能通过名字`subsystemB-dataSource`来引用。当两个子系统构成主应用的时候，主应用可能通过名字`myApp-dataSource`引用数据源，将全部三个名字引用同一个对象，你可以将下面的别名定义添加到应用配置中：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<alias name="subsystemA-dataSource" alias="subsystemB-dataSource"/>
	<alias name="subsystemA-dataSource" alias="myApp-dataSource" />
----

现在每个子系统和主应用都可以通过唯一的名称来引用相同的数据源，并且可以保证他们的定义不与任何其他的定义冲突。

.基于Java的配置
****
如果你想使用基于Java的配置，`@Bean`注解可以用来提供别名，详细信息请看
<<beans-java-bean-annotation>> 。
****

[[beans-factory-class]]
==== 实例化bean
bean定义基本上就是用来创建一个或多个对象的配方(recipe,有更合适的翻译?)，当需要一个bean的时候，容器查看配方并且根据bean定义封装的配置元数据创建（或获取）一个实际的对象。

如果你使用基于XML的配置，你可以在`<bean/>`元素通过`class`属性来指定对象的类型。这个`class`属性，实际上是`BeanDefinition`实例中的一个`Class`属性。这个`class`属性通常是必须的（例外情况，查看<<beans-factory-class-instance-factory-method>> 和 <<beans-child-bean-definitions>>），使用`Class`属性的两种方式：

* 通常情况下，直接通过反射调用构造方法来创建bean，和在Java代码中使用`new`有点像。

* 通过静态工厂方法创建，类中包含静态方法。通过调用静态方法返回对象的类型可能和`Class`一样，也可能完全不一样。

****
.内部类名
如果你想配置使用静态的内部类，你必须用内部类的二进制名称。

例如，在`com.example`包下有个`Foo`类，这里类里面有个静态的内部类`Bar`，这种情况下bean定义的`class`属性应该...

`com.example.Foo$Bar`

注意，使用`$`字符来分割外部类和内部类的名称。
****


[[beans-factory-class-ctor]]
===== 通过构造函数实例化
当你使用构造方法来创建bean的时候，Spring对class没有特殊的要求。也就是说，正在开发的类不需要实现任何特定的接口或者以特定的方式进行编码。但是，根据你使用那种类型的IoC来指定bean，你可能需要一个默认（无参）的构造方法。

Spring IoC
容器可以管理几乎所有你想让它管理的类，它不限于管理POJO。大多数Spring用户更喜欢使用POJO（一个默认无参的构造方法和setter,getter方法）。但在容器中使用非bean形式(non-bean style)的类也是可以的。比如遗留系统中的连接池，很显然它与JavaBean规范不符，但Spring也能管理它。

当使用基于XML的元数据配置文件，可以这样来指定bean类：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<bean id="exampleBean" class="examples.ExampleBean"/>

	<bean name="anotherExample" class="examples.ExampleBeanTwo"/>
----

给构造方法指定参数以及为bean实例化设置属性将在后面的<<beans-factory-collaborators,依赖注入>>中详细说明。


[[beans-factory-class-static-factory-method]]
===== 使用静态工厂方法实例化
当采用静态工厂方法创建bean时，除了需要指定class属性外，还需要通过factory-method属性来指定创建bean实例的工厂方法。Spring将调用此方法(其可选参数接下来介绍)返回实例对象，就此而言，跟通过普通构造器创建类实例没什么两样。

下面的bean定义展示了如何通过工厂方法来创建bean实例。注意，此定义并未指定返回对象的类型，仅指定该类包含的工厂方法。在此例中，`createInstance()`必须是一个__static__方法。

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<bean id="clientService"
		class="examples.ClientService"
		factory-method="createInstance"/>
----

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class ClientService {
		private static ClientService clientService = new ClientService();
		private ClientService() {}

		public static ClientService createInstance() {
			return clientService;
		}
	}
----

给工厂方法指定参数以及为bean实例设置属性的详细内容请查阅<<beans-factory-properties-detailed,依赖和配置详解>>。


[[beans-factory-class-instance-factory-method]]
===== 使用实例工厂方法实例化
与通过 <<beans-factory-class-static-factory-method,静态工厂方法>> 实例化类似，通过调用工厂实例的非静态方法进行实例化。
使用这种方式时，class属性必须为空，而factory-bean属性必须指定为当前(或其祖先)容器中包含工厂方法的bean的名称，而该工厂bean的工厂方法本身必须通过factory-method属性来设定。

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<!-- 工厂bean，包含createInstance()方法 -->
	<bean id="serviceLocator" class="examples.DefaultServiceLocator">
		<!-- 其他需要注入的依赖项 -->
	</bean>

	<!-- 通过工厂bean创建的ben -->
	<bean id="clientService"
		factory-bean="serviceLocator"
		factory-method="createClientServiceInstance"/>
----

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class DefaultServiceLocator {

		private static ClientService clientService = new ClientServiceImpl();
		private DefaultServiceLocator() {}

		public ClientService createClientServiceInstance() {
			return clientService;
		}
	}
----

一个工厂类也可以有多个工厂方法，如下代码所示：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<bean id="serviceLocator" class="examples.DefaultServiceLocator">
		<!-- 其他需要注入的依赖项 -->
	</bean>

	<bean id="clientService"
		factory-bean="serviceLocator"
		factory-method="createClientServiceInstance"/>

	<bean id="accountService"
		factory-bean="serviceLocator"
		factory-method="createAccountServiceInstance"/>
----

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class DefaultServiceLocator {

		private static ClientService clientService = new ClientServiceImpl();
		private static AccountService accountService = new AccountServiceImpl();

		private DefaultServiceLocator() {}

		public ClientService createClientServiceInstance() {
			return clientService;
		}

		public AccountService createAccountServiceInstance() {
			return accountService;
		}

	}
----

这种做法表明工厂bean本身也可以通过依赖注入（DI）进行管理配置。查看<<beans-factory-properties-detailed,依赖和配置详解>>。

[NOTE]
====
在Spring文档中，__factory bean__是指在Spring容器中配置的工厂类通过
<<beans-factory-class-instance-factory-method,实例>> 或
<<beans-factory-class-static-factory-method,静态>> 工厂方法来创建对象。相比而言,
`FactoryBean` (注意大小写) 代表了Spring中特定的
<<beans-factory-extension-factorybean, `FactoryBean` >>.
====




