[[spring-appendices]]
= Appendices





[[migration-4.0]]
== Migrating to Spring Framework 4.0
Migration guides for upgrading from previous releases of the Spring Framework are now
provided as a Wiki page. For details please refer to
https://github.com/spring-projects/spring-framework/wiki/Migrating-from-earlier-versions-of-the-spring-framework





[[classic-spring]]
== Classic Spring Usage
This appendix discusses some classic Spring usage patterns as a reference for developers
maintaining legacy Spring applications. These usage patterns no longer reflect the
recommended way of using these features and the current recommended usage is covered in
the respective sections of the reference manual.




[[classic-spring-orm]]
=== Classic ORM usage
This section documents the classic usage patterns that you might encounter in a legacy
Spring application. For the currently recommended usage patterns, please refer to the
<<orm>> chapter.



[[classic-spring-hibernate]]
==== Hibernate
For the currently recommended usage patterns for Hibernate see <<orm-hibernate>>


