[[validation]]
== 数据校验、数据绑定和类型转换




[[validation-introduction]]
=== 概述

.JSR-303/JSR-349 Bean Validation
****
Spring 4.0 默认即支持Bean Validation 1.0 (JSR-303)和 Bean Validation 1.1(JSR-349)校验规范,
同时也能适配Spring的`Validator`校验接口。

应用既可以像<<validation-beanvalidation>>所述一次性开启全局的Bean Validation，也可以在你
需要验证的地方一一开启。

应用可以像<<validation-binder>>所述在每个`DataBinder`实例中注册多个自定义的Spring `Validator`
实例，这对那些不愿意使用注解来实现插件式的校验逻辑来说非常有用。
****

在业务逻辑中考虑数据校验利弊参半，Spring 提供的校验(和数据绑定)方案也未能解决这个问题。
能明确的是数据校验不应该被限定在web层使用，它应该能很方便的执行本地化，并且能在任何需要
数据校验的场合以插件的形式提供服务。基于以上考虑，Spring 设计了一个既基本又方便使用且能
在所有层使用的`Validator`接口。

Spring 提供了我们称作`DataBinder`的对象来处理数据绑定，所谓的数据绑定就是将用户的输入
自动的绑定到我们的领域模型(或者说任意用来处理用户输入的对象)。Spring 的`Validator`和
`DataBinder`构成了`validation`包，这个包主要被Spring MVC框架使用，但绝不限于只能在该
框架使用。

在Spring中`BeanWrapper`是一个很基本的概念，在很多地方都有使用到它。但是，你可能从来都没有
直接使用到它。鉴于这是一份参考文档，我们认为很有必要对`BeanWrapper`进行必要的解释。在这一
章中我们将解释`BeanWrapper`，在你尝试将数据绑定到对象时一定会使用到它。

Spring的数据绑定和较低级别的BeanWrapper都会使用PropertyEditors来进行转换和格式化。`PropertyEditor`
是JavaBeans规范的一部分，在这一章中我们将进行探讨。Spring3引入了"core.convert"这个包来提供通用
的类型转换工具和高级"format"包来格式化UI显示；这两个包提供的工具可以用作PropertyEditors
的替代品，我们也将在这一章对它们展开讨论。


[[validator]]
=== 使用Spring的Validator接口来进行数据校验

Spring 提供了`Validator`接口用来进行对象的数据校验。`Validator`接口在进行数据校验的时候
会要求传入一个`Errors`对象，当有错误产生时会将错误信息放入该`Errors`对象。

我们假设有这么一个数据对象：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class Person {

		private String name;
		private int age;
		
		// 省略getters和setters...
	}
----

为了给`Person`类提供校验行为我们可以通过实现`org.springframework.validation.Validator`这个接口的两个方法来实现：

* `supports(Class)` - 判断该`Validator`是否能校验提供的`Class`的实例?
* `validate(Object, org.springframework.validation.Errors)` - 校验给定的对象，如果有校验失败信息，将其放入`Errors`对象

实现一个校验器是相当简单的，尤其是当你知道spring已经提供了一个`ValidationUtils`工具类时。

[source,java,indent=0]
[subs="verbatim"]
----
	public class PersonValidator implements Validator {

		/**
		 * 这个校验器*仅仅*只校验Person实例
		 */
		public boolean supports(Class clazz) {
			return Person.class.equals(clazz);
		}

		public void validate(Object obj, Errors e) {
			ValidationUtils.rejectIfEmpty(e, "name", "name.empty");
			Person p = (Person) obj;
			if (p.getAge() < 0) {
				e.rejectValue("age", "negativevalue");
			} else if (p.getAge() > 110) {
				e.rejectValue("age", "too.darn.old");
			}
		}
	}
----

如同你看到的，`ValidationUtils`中的静态方法`rejectIfEmpty(..)`用来拒绝`'name'`这个属性当它为`null`或空字符串时。
你可以看看`ValidationUtils`的javadocs，提前了解下除了例子中展示的功能外还有哪些好用的方法。

当校验一个复杂的对象时，自定义一个校验器类（封装嵌套对象的校验器类）比把校验逻辑分散到各个嵌套对象会更方便管理。
比如:现在有一个`Customer`复杂对象，它有两个`String`类型的属性（first and second name），以及一个`Address`对象；
这个`Address`对象和`Customer`对象是毫无关系的，它还实现了`AddressValidator`这样一个校验器。如果你想在`Customer`校验器
类中重用`Address`校验器的功能（这种重用不是通过简单的代码拷贝），你可以将`Address`校验器的实例通过依赖注入的方式注入到
`Customer`校验器中。
像下面所描述的这样：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class CustomerValidator implements Validator {

		private final Validator addressValidator;

		public CustomerValidator(Validator addressValidator) {
			if (addressValidator == null) {
				throw new IllegalArgumentException("The supplied [Validator] is " +
					"required and must not be null.");
			}
			if (!addressValidator.supports(Address.class)) {
				throw new IllegalArgumentException("The supplied [Validator] must " +
					support the validation of [Address] instances.");
			}
			this.addressValidator = addressValidator;
		}

		/**
		 * 这个校验器校验Customer实例，同时也会校验Customer的子类实例
		 */
		public boolean supports(Class clazz) {
			return Customer.class.isAssignableFrom(clazz);
		}

		public void validate(Object target, Errors errors) {
			ValidationUtils.rejectIfEmptyOrWhitespace(errors, "firstName", "field.required");
			ValidationUtils.rejectIfEmptyOrWhitespace(errors, "surname", "field.required");
			Customer customer = (Customer) target;
			try {
				errors.pushNestedPath("address");
				ValidationUtils.invokeValidator(this.addressValidator, customer.getAddress(), errors);
			} finally {
				errors.popNestedPath();
			}
		}
	}
----

校验错误都会向作为参数传入的`Errors`对象进行报告。如果你使用的是Spring Web MVC，你可以使用`<spring:bind/>`标签
来提取校验错误信息，当然你也可以通过自己的方式来提取错误信息，这些方式可以通过阅读javadocs来获取更多的帮助。

[[validation-conversion]]
=== 通过错误编码得到错误信息

    前面我们谈到数据绑定和数据校验。如何拿到校验错误信息是我们最后需要讨论的一个问题。在上面的例子中，
我们拒绝了`name`和`age`属性。如果我们想要输出校验错误的提示信息，就要用到校验失败时设置的错误编码(本例中就是'name'和'age')。
当你调用`Errors`接口中的`rejectValue`方法或者它的任何一个方法，它的优先实现不仅仅会注册作为参数传入进来的错误编码，
还会注册一些遵循一定规则的错误编码。注册哪些规则的错误编码取决于你使用的`MessageCodesResolver`。当我们使用默认的`DefaultMessageCodesResolver`
时，除了会将错误信息注册到你指定的错误编码上之外，这些错误信息还会注册到包含属性名的错误编码上。假如你调用这样一个方法`rejectValue("age", "too.darn.old")`，
Spring除了会注册`too.darn.old`这个错误编码外，还会注册`too.darn.old.age`和`too.darn.old.age.int`这两个错误编码（即一个是包含属性名，另外一个既包含属性名还包含
类型）；这在Spring中作为一种约定，这样所有的开发者都能按照这种约定来定位错误信息了。

想要获取更多有关`MessageCodesResolver`和默认的策略，可以通过下面的在线文档获取：
{javadoc-baseurl}/org/springframework/validation/MessageCodesResolver.html[`MessageCodesResolver`]
{javadoc-baseurl}/org/springframework/validation/DefaultMessageCodesResolver.html[`DefaultMessageCodesResolver`],


[[beans-beans]]
=== Bean的操作和BeanWrapper
	`org.springframework.beans`包是符合Oracle公司的JavaBeans规范的。JavaBean是一个拥有默认无参构造函数的类，
它还有一种命名约定，假如这个类有一个属性`bingoMadness`，那它必须有一个setter方法`setBingoMadness(..)`和
一个getter方法`getBingoMadness()`。为了获取更多关于JavaBeans及其规范的信息，请参考Oracle的网站(
http://docs.oracle.com/javase/6/docs/api/java/beans/package-summary.html[javabeans])

在beans包中相当重要的是`BeanWrapper`接口和它的实现类（`BeanWrapperImpl`）。引用其javadocs中的说明，`BeanWrapper`提供了设置和获取属性值，
获取属性描述符以及遍历属性来确定它们是可读的还是可写的功能。`BeanWrapper`也支持嵌套属性，允许不限嵌套级数的子属性设置。`BeanWrapper`还支持
在不需要目标类中加入额外的代码就能添加标准的JavaBeans`PropertyChangeListeners`和`VetoableChangeListeners`。值得一提的是`BeanWrapper`还支持
索引的属性。通常我们一般不会在应用代码中直接用到`BeanWrapper`，除了`DataBinder`和`BeanFactory`。

`BeanWrapper`基本上是通过它的名字来进行工作的：它包裹一个bean来代替它执行某些动作，如设置以及获取属性。


[[beans-beans-conventions]]
==== Setting和getting基本及嵌套属性
Setting和getting属性是通过一组变形的重载方法`setPropertyValue(s)`和`getPropertyValue(s)`来完成的。您可以通过Spring的javadoc来获得更多的信息。
你必须知道的是描述对象的属性有一些约定俗成的规则。下面有几个例子：

[[beans-beans-conventions-properties-tbl]]
.属性的例子
|===
| 表达式| 解释(说明)

| `name`
| 表示通过方法`getName()`或`isName()`和`setName(..)`来操作属性`name`

| `account.name`
| 表示通过方法`getAccount().setName()`或`getAccount().getName()`来操作`account`的嵌套属性`name`

| `account[2]`
| 表示索引属性`account`的第三个元素。能被索引的属性可以是`array`, `list`或者其他实现了有序集合的类型。

| `account[COMPANYNAME]`
| 表示指定Map `account`以__COMPANYNAME__为键的值

|===

下面你将看到一些通过`BeanWrapper`来获取和设置属性的例子。

__(下面这一节对那些不想在工作中直接用到`BeanWrapper`的人来说不是那么的重要。如果你只是会用到`DataBinder`和`BeanFactory`
这类开箱即用的实现，你可以直接跳过这里，直接关注`PropertyEditors`这一节。)__

假如有下面这两个类：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class Company {

		private String name;
		private Employee managingDirector;

		public String getName() {
			return this.name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public Employee getManagingDirector() {
			return this.managingDirector;
		}

		public void setManagingDirector(Employee managingDirector) {
			this.managingDirector = managingDirector;
		}
	}
----

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public class Employee {

		private String name;

		private float salary;

		public String getName() {
			return this.name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public float getSalary() {
			return salary;
		}

		public void setSalary(float salary) {
			this.salary = salary;
		}
	}
----

下面的代码快照向你展示了如何获取和操作已经实例化的`Companies`和`Employees`的属性。

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	BeanWrapper company = BeanWrapperImpl(new Company());
	// 设置公司名称..
	company.setPropertyValue("name", "Some Company Inc.");
	// ...也可以像这样做:
	PropertyValue value = new PropertyValue("name", "Some Company Inc.");
	company.setPropertyValue(value);

	// 现在我们来创建一个主管并把它绑定到公司上:
	BeanWrapper jim = BeanWrapperImpl(new Employee());
	jim.setPropertyValue("name", "Jim Stravinsky");
	company.setPropertyValue("managingDirector", jim.getWrappedInstance());

	// 通过公司属性来获取主管的薪水
	Float salary = (Float) company.getPropertyValue("managingDirector.salary");
----



