[[aop-pointcuts]]
==== Declaring a pointcut
Recall that pointcuts determine join points of interest, and thus enable us to control
when advice executes. __Spring AOP only supports method execution join points for Spring
beans__, so you can think of a pointcut as matching the execution of methods on Spring
beans. A pointcut declaration has two parts: a signature comprising a name and any
parameters, and a pointcut expression that determines __exactly__ which method
executions we are interested in. In the @AspectJ annotation-style of AOP, a pointcut
signature is provided by a regular method definition, and the pointcut expression is
indicated using the `@Pointcut` annotation (the method serving as the pointcut signature
__must__ have a `void` return type).

An example will help make this distinction between a pointcut signature and a pointcut
expression clear. The following example defines a pointcut named `'anyOldTransfer'` that
will match the execution of any method named `'transfer'`:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	@Pointcut("execution(* transfer(..))")// the pointcut expression
	private void anyOldTransfer() {}// the pointcut signature
----

The pointcut expression that forms the value of the `@Pointcut` annotation is a regular
AspectJ 5 pointcut expression. For a full discussion of AspectJ's pointcut language, see
the http://www.eclipse.org/aspectj/doc/released/progguide/index.html[AspectJ
Programming Guide] (and for extensions, the
http://www.eclipse.org/aspectj/doc/released/adk15notebook/index.html[AspectJ 5
Developers Notebook]) or one of the books on AspectJ such as "Eclipse AspectJ" by Colyer
et. al. or "AspectJ in Action" by Ramnivas Laddad.


[[aop-pointcuts-designators]]
===== Supported Pointcut Designators
Spring AOP supports the following AspectJ pointcut designators (PCD) for use in pointcut
expressions:

.Other pointcut types
****
The full AspectJ pointcut language supports additional pointcut designators that are not
supported in Spring. These are: `call, get, set, preinitialization,
staticinitialization, initialization, handler, adviceexecution, withincode, cflow,
cflowbelow, if, @this`, and `@withincode`. Use of these pointcut designators in pointcut
expressions interpreted by Spring AOP will result in an `IllegalArgumentException` being
thrown.

The set of pointcut designators supported by Spring AOP may be extended in future
releases to support more of the AspectJ pointcut designators.
****

* __execution__ - for matching method execution join points, this is the primary
  pointcut designator you will use when working with Spring AOP
* __within__ - limits matching to join points within certain types (simply the execution
  of a method declared within a matching type when using Spring AOP)
* __this__ - limits matching to join points (the execution of methods when using Spring
  AOP) where the bean reference (Spring AOP proxy) is an instance of the given type
* __target__ - limits matching to join points (the execution of methods when using
  Spring AOP) where the target object (application object being proxied) is an instance
  of the given type
* __args__ - limits matching to join points (the execution of methods when using Spring
  AOP) where the arguments are instances of the given types
* __@target__ - limits matching to join points (the execution of methods when using
  Spring AOP) where the class of the executing object has an annotation of the given type
* __@args__ - limits matching to join points (the execution of methods when using Spring
  AOP) where the runtime type of the actual arguments passed have annotations of the
  given type(s)
* __@within__ - limits matching to join points within types that have the given
  annotation (the execution of methods declared in types with the given annotation when
  using Spring AOP)
* __@annotation__ - limits matching to join points where the subject of the join point
  (method being executed in Spring AOP) has the given annotation

Because Spring AOP limits matching to only method execution join points, the discussion
of the pointcut designators above gives a narrower definition than you will find in the
AspectJ programming guide. In addition, AspectJ itself has type-based semantics and at
an execution join point both '++this++' and '++target++' refer to the same object - the
object executing the method. Spring AOP is a proxy-based system and differentiates
between the proxy object itself (bound to '++this++') and the target object behind the
proxy (bound to '++target++').

[NOTE]
====
Due to the proxy-based nature of Spring's AOP framework, protected methods are by
definition __not__ intercepted, neither for JDK proxies (where this isn't applicable)
nor for CGLIB proxies (where this is technically possible but not recommendable for AOP
purposes). As a consequence, any given pointcut will be matched against __public methods
only__!

If your interception needs include protected/private methods or even constructors,
consider the use of Spring-driven <<aop-aj-ltw,native AspectJ weaving>> instead of
Spring's proxy-based AOP framework. This constitutes a different mode of AOP usage with
different characteristics, so be sure to make yourself familiar with weaving first
before making a decision.
====

Spring AOP also supports an additional PCD named '++bean++'. This PCD allows you to limit
the matching of join points to a particular named Spring bean, or to a set of named
Spring beans (when using wildcards). The '++bean++' PCD has the following form:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	bean(idOrNameOfBean)
----

The '++idOrNameOfBean++' token can be the name of any Spring bean: limited wildcard
support using the '++*++' character is provided, so if you establish some naming
conventions for your Spring beans you can quite easily write a '++bean++' PCD expression
to pick them out. As is the case with other pointcut designators, the '++bean++' PCD can
be &&'ed, ||'ed, and ! (negated) too.

[NOTE]
====
Please note that the '++bean++' PCD is __only__ supported in Spring AOP - and __not__ in
native AspectJ weaving. It is a Spring-specific extension to the standard PCDs that
AspectJ defines.

The '++bean++' PCD operates at the __instance__ level (building on the Spring bean name
concept) rather than at the type level only (which is what weaving-based AOP is limited
to). Instance-based pointcut designators are a special capability of Spring's
proxy-based AOP framework and its close integration with the Spring bean factory, where
it is natural and straightforward to identify specific beans by name.
====


