[[aop-ataspectj-advice-params-generics]]
====== Advice parameters and generics
Spring AOP can handle generics used in class declarations and method parameters. Suppose
you have a generic type like this:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	public interface Sample<T> {
		void sampleGenericMethod(T param);
		void sampleGenericCollectionMethod(Collection>T> param);
	}
----

You can restrict interception of method types to certain parameter types by simply
typing the advice parameter to the parameter type you want to intercept the method for:

[source,java,indent=0]
[subs="verbatim"]
----
	@Before("execution(* ..Sample+.sampleGenericMethod(*)) && args(param)")
	public void beforeSampleMethod(MyType param) {
		// Advice implementation
	}
----

That this works is pretty obvious as we already discussed above. However, it's worth
pointing out that this won't work for generic collections. So you cannot define a
pointcut like this:

[source,java,indent=0]
[subs="verbatim"]
----
	@Before("execution(* ..Sample+.sampleGenericCollectionMethod(*)) && args(param)")
	public void beforeSampleMethod(Collection<MyType> param) {
		// Advice implementation
	}
----

To make this work we would have to inspect every element of the collection, which is not
reasonable as we also cannot decide how to treat `null` values in general. To achieve
something similar to this you have to type the parameter to `Collection<?>` and manually
check the type of the elements.

[[aop-ataspectj-advice-params-names]]
====== Determining argument names
The parameter binding in advice invocations relies on matching names used in pointcut
expressions to declared parameter names in (advice and pointcut) method signatures.
Parameter names are __not__ available through Java reflection, so Spring AOP uses the
following strategies to determine parameter names:

* If the parameter names have been specified by the user explicitly, then the specified
  parameter names are used: both the advice and the pointcut annotations have
  an optional "argNames" attribute which can be used to specify the argument names of
  the annotated method - these argument names __are__ available at runtime. For example:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	@Before(value="com.xyz.lib.Pointcuts.anyPublicMethod() && target(bean) && @annotation(auditable)",
			argNames="bean,auditable")
	public void audit(Object bean, Auditable auditable) {
		AuditCode code = auditable.value();
		// ... use code and bean
	}
----

If the first parameter is of the `JoinPoint`, `ProceedingJoinPoint`, or
`JoinPoint.StaticPart` type, you may leave out the name of the parameter from the value
of the "argNames" attribute. For example, if you modify the preceding advice to receive
the join point object, the "argNames" attribute need not include it:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	@Before(value="com.xyz.lib.Pointcuts.anyPublicMethod() && target(bean) && @annotation(auditable)",
			argNames="bean,auditable")
	public void audit(JoinPoint jp, Object bean, Auditable auditable) {
		AuditCode code = auditable.value();
		// ... use code, bean, and jp
	}
----

The special treatment given to the first parameter of the `JoinPoint`,
`ProceedingJoinPoint`, and `JoinPoint.StaticPart` types is particularly convenient for
advice that do not collect any other join point context. In such situations, you may
simply omit the "argNames" attribute. For example, the following advice need not declare
the "argNames" attribute:

[source,java,indent=0]
[subs="verbatim,quotes"]
----
	@Before("com.xyz.lib.Pointcuts.anyPublicMethod()")
	public void audit(JoinPoint jp) {
		// ... use jp
	}
----

* Using the `'argNames'` attribute is a little clumsy, so if the `'argNames'` attribute
  has not been specified, then Spring AOP will look at the debug information for the
  class and try to determine the parameter names from the local variable table. This
  information will be present as long as the classes have been compiled with debug
  information ( `'-g:vars'` at a minimum). The consequences of compiling with this flag
  on are: (1) your code will be slightly easier to understand (reverse engineer), (2)
  the class file sizes will be very slightly bigger (typically inconsequential), (3) the
  optimization to remove unused local variables will not be applied by your compiler. In
  other words, you should encounter no difficulties building with this flag on.

[NOTE]
====
If an @AspectJ aspect has been compiled by the AspectJ compiler (ajc) even without the
debug information then there is no need to add the argNames attribute as the compiler
will retain the needed information.
====

* If the code has been compiled without the necessary debug information, then Spring AOP
  will attempt to deduce the pairing of binding variables to parameters (for example, if
  only one variable is bound in the pointcut expression, and the advice method only
  takes one parameter, the pairing is obvious!). If the binding of variables is
  ambiguous given the available information, then an `AmbiguousBindingException` will be
  thrown.
* If all of the above strategies fail then an `IllegalArgumentException` will be thrown.

