[[aop]]
== Aspect Oriented Programming with Spring




[[aop-introduction]]
=== Introduction
__Aspect-Oriented Programming__ (AOP) complements Object-Oriented Programming (OOP) by
providing another way of thinking about program structure. The key unit of modularity in
OOP is the class, whereas in AOP the unit of modularity is the __aspect__. Aspects
enable the modularization of concerns such as transaction management that cut across
multiple types and objects. (Such concerns are often termed __crosscutting__ concerns in
AOP literature.)

One of the key components of Spring is the __AOP framework__. While the Spring IoC
container does not depend on AOP, meaning you do not need to use AOP if you don't want
to, AOP complements Spring IoC to provide a very capable middleware solution.

.Spring 2.0 AOP
****
Spring 2.0 introduces a simpler and more powerful way of writing custom aspects using
either a <<aop-schema,schema-based approach>> or the <<aop-ataspectj,@AspectJ annotation
style>>. Both of these styles offer fully typed advice and use of the AspectJ pointcut
language, while still using Spring AOP for weaving.

The Spring 2.0 schema- and @AspectJ-based AOP support is discussed in this chapter.
Spring 2.0 AOP remains fully backwards compatible with Spring 1.2 AOP, and the
lower-level AOP support offered by the Spring 1.2 APIs is discussed in <<aop-api,the
following chapter>>.
****

AOP is used in the Spring Framework to...

* ... provide declarative enterprise services, especially as a replacement for EJB
  declarative services. The most important such service is
  <<transaction-declarative,__declarative transaction management__>>.
* ... allow users to implement custom aspects, complementing their use of OOP with AOP.

[NOTE]
====
If you are interested only in generic declarative services or other pre-packaged
declarative middleware services such as pooling, you do not need to work directly with
Spring AOP, and can skip most of this chapter.
====



[[aop-introduction-defn]]
==== AOP concepts
Let us begin by defining some central AOP concepts and terminology. These terms are not
Spring-specific... unfortunately, AOP terminology is not particularly intuitive;
however, it would be even more confusing if Spring used its own terminology.

* __Aspect__: a modularization of a concern that cuts across multiple classes.
  Transaction management is a good example of a crosscutting concern in enterprise Java
  applications. In Spring AOP, aspects are implemented using regular classes
  (the <<aop-schema,schema-based approach>>) or regular classes annotated with the
  `@Aspect` annotation (the <<aop-ataspectj, `@AspectJ` style>>).
* __Join point__: a point during the execution of a program, such as the execution of a
  method or the handling of an exception. In Spring AOP, a join point __always__
  represents a method execution.
* __Advice__: action taken by an aspect at a particular join point. Different types of
  advice include "around," "before" and "after" advice. (Advice types are discussed
  below.) Many AOP frameworks, including Spring, model an advice as an __interceptor__,
  maintaining a chain of interceptors __around__ the join point.
* __Pointcut__: a predicate that matches join points. Advice is associated with a
  pointcut expression and runs at any join point matched by the pointcut (for example,
  the execution of a method with a certain name). The concept of join points as matched
  by pointcut expressions is central to AOP, and Spring uses the AspectJ pointcut
  expression language by default.
* __Introduction__: declaring additional methods or fields on behalf of a type. Spring
  AOP allows you to introduce new interfaces (and a corresponding implementation) to any
  advised object. For example, you could use an introduction to make a bean implement an
  `IsModified` interface, to simplify caching. (An introduction is known as an
  inter-type declaration in the AspectJ community.)
* __Target object__: object being advised by one or more aspects. Also referred to as
  the __advised__ object. Since Spring AOP is implemented using runtime proxies, this
  object will always be a __proxied__ object.
* __AOP proxy__: an object created by the AOP framework in order to implement the aspect
  contracts (advise method executions and so on). In the Spring Framework, an AOP proxy
  will be a JDK dynamic proxy or a CGLIB proxy.
* __Weaving__: linking aspects with other application types or objects to create an
  advised object. This can be done at compile time (using the AspectJ compiler, for
  example), load time, or at runtime. Spring AOP, like other pure Java AOP frameworks,
  performs weaving at runtime.

Types of advice:

* __Before advice__: Advice that executes before a join point, but which does not have
  the ability to prevent execution flow proceeding to the join point (unless it throws
  an exception).
* __After returning advice__: Advice to be executed after a join point completes
  normally: for example, if a method returns without throwing an exception.
* __After throwing advice__: Advice to be executed if a method exits by throwing an
  exception.
* __After (finally) advice__: Advice to be executed regardless of the means by which a
  join point exits (normal or exceptional return).
* __Around advice__: Advice that surrounds a join point such as a method invocation.
  This is the most powerful kind of advice. Around advice can perform custom behavior
  before and after the method invocation. It is also responsible for choosing whether to
  proceed to the join point or to shortcut the advised method execution by returning its
  own return value or throwing an exception.

Around advice is the most general kind of advice. Since Spring AOP, like AspectJ,
provides a full range of advice types, we recommend that you use the least powerful
advice type that can implement the required behavior. For example, if you need only to
update a cache with the return value of a method, you are better off implementing an
after returning advice than an around advice, although an around advice can accomplish
the same thing. Using the most specific advice type provides a simpler programming model
with less potential for errors. For example, you do not need to invoke the `proceed()`
method on the `JoinPoint` used for around advice, and hence cannot fail to invoke it.

In Spring 2.0, all advice parameters are statically typed, so that you work with advice
parameters of the appropriate type (the type of the return value from a method execution
for example) rather than `Object` arrays.

The concept of join points, matched by pointcuts, is the key to AOP which distinguishes
it from older technologies offering only interception. Pointcuts enable advice to be
targeted independently of the Object-Oriented hierarchy. For example, an around advice
providing declarative transaction management can be applied to a set of methods spanning
multiple objects (such as all business operations in the service layer).



[[aop-introduction-spring-defn]]
==== Spring AOP capabilities and goals
Spring AOP is implemented in pure Java. There is no need for a special compilation
process. Spring AOP does not need to control the class loader hierarchy, and is thus
suitable for use in a Servlet container or application server.

Spring AOP currently supports only method execution join points (advising the execution
of methods on Spring beans). Field interception is not implemented, although support for
field interception could be added without breaking the core Spring AOP APIs. If you need
to advise field access and update join points, consider a language such as AspectJ.

Spring AOP's approach to AOP differs from that of most other AOP frameworks. The aim is
not to provide the most complete AOP implementation (although Spring AOP is quite
capable); it is rather to provide a close integration between AOP implementation and
Spring IoC to help solve common problems in enterprise applications.

Thus, for example, the Spring Framework's AOP functionality is normally used in
conjunction with the Spring IoC container. Aspects are configured using normal bean
definition syntax (although this allows powerful "autoproxying" capabilities): this is a
crucial difference from other AOP implementations. There are some things you cannot do
easily or efficiently with Spring AOP, such as advise very fine-grained objects (such as
domain objects typically): AspectJ is the best choice in such cases. However, our
experience is that Spring AOP provides an excellent solution to most problems in
enterprise Java applications that are amenable to AOP.

Spring AOP will never strive to compete with AspectJ to provide a comprehensive AOP
solution. We believe that both proxy-based frameworks like Spring AOP and full-blown
frameworks such as AspectJ are valuable, and that they are complementary, rather than in
competition. Spring seamlessly integrates Spring AOP and IoC with AspectJ, to enable
all uses of AOP to be catered for within a consistent Spring-based application
architecture. This integration does not affect the Spring AOP API or the AOP Alliance
API: Spring AOP remains backward-compatible. See <<aop-api,the following chapter>> for a
discussion of the Spring AOP APIs.

[NOTE]
====
One of the central tenets of the Spring Framework is that of __non-invasiveness__; this
is the idea that you should not be forced to introduce framework-specific classes and
interfaces into your business/domain model. However, in some places the Spring Framework
does give you the option to introduce Spring Framework-specific dependencies into your
codebase: the rationale in giving you such options is because in certain scenarios it
might be just plain easier to read or code some specific piece of functionality in such
a way. The Spring Framework (almost) always offers you the choice though: you have the
freedom to make an informed decision as to which option best suits your particular use
case or scenario.

One such choice that is relevant to this chapter is that of which AOP framework (and
which AOP style) to choose. You have the choice of AspectJ and/or Spring AOP, and you
also have the choice of either the @AspectJ annotation-style approach or the Spring XML
configuration-style approach. The fact that this chapter chooses to introduce the
@AspectJ-style approach first should not be taken as an indication that the Spring team
favors the @AspectJ annotation-style approach over the Spring XML configuration-style.

See <<aop-choosing>> for a more complete discussion of the whys and wherefores of each
style.
====



[[aop-introduction-proxies]]
==== AOP Proxies
Spring AOP defaults to using standard JDK __dynamic proxies__ for AOP proxies. This
enables any interface (or set of interfaces) to be proxied.

Spring AOP can also use CGLIB proxies. This is necessary to proxy classes, rather than
interfaces. CGLIB is used by default if a business object does not implement an
interface. As it is good practice to program to interfaces rather than classes, business
classes normally will implement one or more business interfaces. It is possible to
<<aop-autoproxy-force-CGLIB,force the use of CGLIB>>, in those (hopefully rare) cases
where you need to advise a method that is not declared on an interface, or where you
need to pass a proxied object to a method as a concrete type.

It is important to grasp the fact that Spring AOP is __proxy-based__. See
<<aop-understanding-aop-proxies>> for a thorough examination of exactly what this
implementation detail actually means.
